apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
  namespace: ecommerce-backend-api
spec:
  provider: aws
  secretObjects:
    - secretName: api-secrets
      type: Opaque
      data:
        - objectName: "my-api-secret"   # this is the full secret object in Secrets Manager
          key: MONGODB_URI
        - objectName: "my-api-secret"
          key: PORT
        - objectName: "my-api-secret"
          key: PASS_SEC
        - objectName: "my-api-secret"
          key: JWT_SEC
  parameters:
    objects: |
      - objectName: "my-api-secret"
        objectType: "secretsmanager"
