apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
  namespace: ecommerce-backend-api
spec:
  provider: aws
  secretObjects:
    - secretName: api-secrets
      type: Opaque
      data:
        - objectName: PORT
          key: PORT
        - objectName: MONGODB_URI
          key: MONGODB_URI
        - objectName: PASS_SEC
          key: PASS_SEC
        - objectName: JWT_SEC
          key: JWT_SEC
  parameters:
    objects: |
      - objectName: "my-api-secret"
        objectType: "secretsmanager"
        jmesPath:
          - path: PORT
            objectAlias: PORT
          - path: MONGODB_URI
            objectAlias: MONGODB_URI
          - path: PASS_SEC
            objectAlias: PASS_SEC
          - path: JWT_SEC
            objectAlias: JWT_SEC
