apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: ecommerce-backend-api
  labels:
    role: api
    env: demo
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: api
  template:
    metadata:
      labels:
        role: api
    spec:
      imagePullSecrets:
      - name: ecr-registry-secret
      containers:
      - name: api
        image: 951405501907.dkr.ecr.ap-south-1.amazonaws.com/learning-devops/react-native-ecommerce-api:9
        imagePullPolicy: Always
        envFrom:
            - secretRef:
                name: api-secrets
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 2
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
        startupProbe:
          httpGet:
            path: /started
            port: 8000
          initialDelaySeconds: 0
          periodSeconds: 10
          failureThreshold: 30
